#########################################################################################################################
##                                                                                                                     ##
## author  : Yan                                                                                                       ##
## email   : yan-wyb@foxmail.com                                                                                       ##
## Github  ; https://github.com/yan-wyb                                                                                ##
## Website : www.yan-wyb.com                                                                                           ##
##                                                                                                                     ##
#########################################################################################################################

# If you have any plugins, put them here!
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
group :jekyll_plugins do
    gem 'jekyll-feed'
    gem 'jekyll-sitemap'
    gem 'jekyll-paginate'
    gem 'jekyll-seo-tag'
    gem 'jekyll-archives'
    gem 'kramdown'
    gem 'rouge'
	gem "jekyll-last-modified-at"
end

#source "http://production.cf.rubygems.org/"

gem "github-pages",">= 204"
gem "pygments.rb"
